
<?php
$this->title = "My Albums";
$this->headTitle($this->title);

?>
<?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
<p><a href="<?php echo $this->url(array('controller'=>'index',
        'action'=>'add'));?>">Add new album</a></p>
    <?php endif; ?>
<table>
<tr>
    <th>Title</th>
    <th>Artist</th>
    <th> &nbsp </th>
</tr>

<?php foreach($this->albums as $album) : ?>
<tr>
    <td><?php echo $this->escape($album->title);?></td>
    <td><?php echo $this->escape($album->artist);?></td>
   <?php if(Zend_Auth::getInstance()->hasIdentity()): ?>
<td>
        <a href="<?php echo $this->url(array('controller'=>'index',
            'action'=>'edit', 'id'=>$album->id));?>">Edit</a>
        <a href="<?php echo $this->url(array('controller'=>'index',
            'action'=>'delete', 'id'=>$album->id));?>">Delete</a>
    </td>
<?php endif; ?>
</tr>
<?php endforeach; ?>

</table>
<?php echo $this->paginationControl($this->albums, 'Sliding', 'pagination.phtml'); ?>
<?php
if(!Zend_Auth::getInstance()->hasIdentity())
{
echo $this->SignIn;
echo $this->SignUpError;
}
?>